/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_cordova_CTYMediaEditor_Mp3LameWraper */

#ifndef _Included_org_apache_cordova_CTYMediaEditor_Mp3LameWraper
#define _Included_org_apache_cordova_CTYMediaEditor_Mp3LameWraper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_cordova_CTYMediaEditor_Mp3LameWraper
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_cordova_CTYMediaEditor_Mp3LameWraper_close
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_cordova_CTYMediaEditor_Mp3LameWraper
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_org_apache_cordova_CTYMediaEditor_Mp3LameWraper_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     org_apache_cordova_CTYMediaEditor_Mp3LameWraper
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_apache_cordova_CTYMediaEditor_Mp3LameWraper_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_apache_cordova_CTYMediaEditor_Mp3LameWraper
 * Method:    init
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_org_apache_cordova_CTYMediaEditor_Mp3LameWraper_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
